persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout

# --- LISTENER MQTT ESTÁNDAR (TCP) ---
# Importante: 0.0.0.0 permite conexiones desde fuera del contenedor
listener 1883 0.0.0.0
protocol mqtt
allow_anonymous true

# --- LISTENER WEBSOCKETS (Para Grafana o Cloudflare futuro) ---
listener 9001 0.0.0.0
protocol websockets
allow_anonymous true