persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout

# --- IMPORTANTE PARA DOCKER ---
# Escuchar en el puerto 1883 para todas las interfaces (0.0.0.0)
listener 1883

# Permitir conexiones sin usuario/contraseña (para empezar fácil)
allow_anonymous true