; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp07]
platform = espressif8266
board = esp07
framework = esp8266-rtos-sdk

lib_deps =
    https://github.com/Daven14/ESP8266_NONOS_SDK @ ^1.0.0

build_flags =
    -I"$PROJECT_DIR/include"
    -I"$PLATFORMIO_HOME_DIR/packages/framework-esp8266-rtos-sdk/include"
    -I"$PLATFORMIO_HOME_DIR/packages/framework-esp8266-rtos-sdk/extra_include"
    -I"$PLATFORMIO_HOME_DIR/packages/framework-esp8266-rtos-sdk/driver_lib/include"
    -DICACHE_FLASH
