 SET NAMES utf8mb4;
CREATE DATABASE IF NOT EXISTS seismic_iot
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;
USE seismic_iot;

-- sql_mode recomendado (warning-safe en 8.0)
SET @OLD_SQL_MODE := @@SQL_MODE;
SET SESSION sql_mode = 'STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';

SET @OLD_FK := @@FOREIGN_KEY_CHECKS;
SET FOREIGN_KEY_CHECKS = 0;
START TRANSACTION;

